package elderlysitter.capstone.enumCode;

public enum StatusCode {
    ACTIVATE,
    DEACTIVATE,
    WAITING_FOR_SITTER,
    WAITING_FOR_DATE,
    NEW,
    REJECTED,
    CANCEL,
    STARTING,
    WAITING_FOR_CUSTOMER_CHECK,
    WAITING_FOR_NEXT_DATE,
    DONE,
    WAITING_FOR_CUSTOMER_PAYMENT,
    SITTER_NOT_FOUND
}
