package elderlysitter.capstone.enumCode;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


public enum SuccessCode {
    FIND_SUCCESS,
    CANCEL_SUCCESS,
    LOGOUT_SUCCESS,
    UPDATE_SUCCESS,
    SUCCESS,
    FIND_ALL_SUCCESS,
    FIND_ALL_REPORT_SUCCESS,
    APPROVE_UP_SALARY_SUCCESS,
    REJECT_UP_SALARY_SUCCESS,
    GET_FORMS_SALARY_SUCCESS,
    UP_SALARY_SUCCESS,
    REDUCE_SUCCESS,
    FIND_ALL_WORKING_TIME_SUCCESS,
    FORGOT_PASSWORD_SUCCESS,
    LOGIN_SUCCESS,
    SITTER_CANCEL_SUCCESS,
    ADD_ELDER_SUCCESS,
    UPDATE_ELDER_SUCCESS,
    REMOVE_ELDER_SUCCESS,
    FIND_ALL_ELDER_SUCCESS,
    FIND_ELDER_SUCCESS,
    ADD_CATEGORY_SUCCESS,
    FIND_ALL_CATEGORY_SUCCESS,
    ADD_SERVICE_SUCCESS,
    UPDATE_SERVICE_SUCCESS,
    ACTIVE_SERVICE_SUCCESS,
    DEACTIVATE_SERVICE_SUCCESS,
    FIND_ALL_SERVICE_SUCCESS,
    ADD_CUSTOMER_SUCCESS,
    UPDATE_CUSTOMER_SUCCESS,
    BAN_CUSTOMER_SUCCESS,
    UNBAN_CUSTOMER_SUCCESS,
    FIND_ALL_CUSTOMER_SUCCESS,
    FIND_CUSTOMER_SUCCESS,
    CHANGE_PASSWORD_SUCCESS,
    ADD_CANDIDATE_SUCCESS,
    ACCEPT_CANDIDATE_SUCCESS,
    REJECT_CANDIDATE_SUCCESS,
    FIND_ALL_CANDIDATE_SUCCESS,
    FIND_CANDIDATE_SUCCESS,
    FIND_ALL_SITTER_SUCCESS,
    ACTIVATE_SITTER_SUCCESS,
    DEACTIVATE_SITTER_SUCCESS,
    FIND_SITTER_SUCCESS,
    UPDATE_SITTER_SUCCESS,
    ADD_BOOKING_SUCCESS,
    FIND_ALL_BOOKING_SUCCESS,
    FIND_BOOKING_SUCCESS,
    ACCEPT_BOOKING_SUCCESS,
    FIND_SERVICE_SUCCESS,
    COUNT_BOOKING_SUCCESS,
    GET_REVENUE_SUCCESS,
    REPORT_SERVICE_SUCCESS,
    PAID_SUCCESS,
    CHECK_IN_SUCCESS,

    CHECK_BOOKING_SUCCESS,
    CHECK_OUT_SUCCESS,
    RATE_SUCCESS,

    REPORT_SUCCESS






}
